# Generated by Django 2.1.15 on 2020-02-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=64)),
                ('sensor_name', models.CharField(max_length=250)),
                ('sensor_value', models.CharField(max_length=64)),
            ],
        ),
    ]
